name: Codacy Coverage Reporter

on:
  push:
    branches:
      - develop

jobs:
  test-and-report:
    runs-on: ubuntu-latest
    name: Test and Report
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run coverage
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/lcov.info
